version: 3

tasks:
  preBuild:
    cmds:
      - go mod download
      - go mod tidy
      - go generate ./...

  build:
    desc: Build
    deps: [ preBuild ]
    cmds:
      - go build .

  dependencyUpdates:
    desc: Show dependency updates
    deps: [ preBuild ]
    cmds:
      - go list -u -m -json all | go-mod-outdated -update -direct
